### ISSUE TITLE
lack of data..........

### ISSUE THREAD

**Issue by SeekPoint** [michaelfarrell76/End-To-End-Generative-Dialogue#2]
rzai@rzai00:~/prj/End-To-End-Generative-Dialogue/src$ python preprocess.py
Traceback (most recent call last):
  File "preprocess.py", line 656, in <module>
    sys.exit(main(sys.argv[1:]))
  File "preprocess.py", line 652, in main
    format_data(args)
  File "preprocess.py", line 396, in format_data
    data_dict = load_data()
  File "preprocess.py", line 352, in load_data
    with open('%s%s/%s' % (args.input_directory, data_set, data_file)) as f:
IOError: [Errno 2] No such file or directory: '../data/MovieTriples/Training.dict.pkl'
rzai@rzai00:~/prj/End-To-End-Generative-Dialogue/src$

**Comment by michaelfarrell76** [comment]
We do not have permission to distribute the dataset but you can reach out to the authors of the original paper and they most likely will grant you access:

https://arxiv.org/pdf/1507.04808.pdf https://arxiv.org/pdf/1507.04808.pdf

Mike
