### ISSUE TITLE
MovieTriples dataset for research

### ISSUE THREAD

**Issue by Zaiku1972** [michaelfarrell76/End-To-End-Generative-Dialogue#4]
can you please give me the MovieTriples dataset, I am doing it for a personal research project.

my email is: sriramarvind95@gmail.com 

Thanks

**Comment by evelinehong** [comment]
Would you please give me the MovieTriples dataset?
email:evelinehong@sjtu.edu.cn
Thx a lot.

**Comment by belainine** [comment]
can you please give me the MovieTriples dataset, I am doing it for a personal research project.

my email is: belainine.billal@hotmail.com

Thanks

**Comment by sshleifer** [comment]
can you please give me the MovieTriples dataset, I am doing it for a research project.

my email is: sshleifer@gmail.com

Thanks!

**Comment by K-Square-00** [comment]
Could you please give me the MovieTriples dataset, I am doing it for my research project on chatbot.

my email is: kan.kan.zhou@outlook.com

Thanks!

**Comment by michaelfarrell76** [comment]
i am not licensed to distribute the dataset, please reach out to the authors of the original paper: https://arxiv.org/abs/1507.04808

(i also do not have permission to distribute their email address)
